services:
  db:
    container_name: patient-service-db
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient-db


#  app:
#    container_name: patient-service-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "4000:4000"
#    depends_on:
#      - db


