version: '3.8'

services:
  app:
    container_name: patient-service-app
    build: .
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient-service-db
      BILLING_SERVICE_ADDRESS: billing-service-app
      BILLING_SERVICE_GRPC_PORT: 9001
    depends_on:
      - db
    networks:
      - patient-management

  db:
    image: postgres:17.4
    container_name: patient-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient-service-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - patient-management

volumes:
  postgres_data:

networks:
  patient-management:
    external: true