### PATCH request to example server
PATCH http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174004
Content-Type: application/json

{
  "name": "John Doe2",
  "email": "test@exsample.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}

###