version: '3.8'

services:
  app:
    container_name: billing-service-app
    build: .
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/billing-service-db
    networks:
      - patient-management

networks:
  patient-management:
    external: true